import LZString from "lz-string";

// ─── Sampler-config sharing ───────────────────────────────────────────────────
// Serialize the *minimal* sampler config into a URL-safe blob and back. The app is
// hosted statically (GitHub Pages, no backend), so the whole config rides in the URL.
// Only the authoring inputs travel — never ephemeral output (drawn rows, collected
// statistics, animation/UI state), which are regenerated by re-running the sampler.

// Bump when the serialized SHAPE changes incompatibly; decode rejects unknown majors.
const VERSION = 1;
// Code-known obfuscation key (NOT a secret). A hidden link's config is XOR'd with a key
// derived from this + the salt so a casual decompress of the URL shows garbage — but the
// app can always decode it, so the sampler runs for anyone who opens the link. The user's
// password is never needed to RUN a hidden sampler, only to REVEAL its contents.
const PEPPER = "tinkersim-veil-v1";

// Pull the shareable fields out of full app state (everything else is derived/ephemeral).
function pickConfig(state) {
  return {
    pipeline: state.pipeline,
    sampleSize: state.sampleSize,
    runMode: state.runMode,
    stopRule: state.stopRule,
    trackedStats: state.trackedStats,
    codeLang: state.codeLang,        // Task E (undefined-safe before it lands)
  };
}

// ─── Hidden (password-veiled) helpers — NOT crypto-grade ──────────────────────
// A hidden link opens and RUNS for anyone (its config is recoverable with the code-known
// PEPPER, not the password); the password only gates REVEALING the device internals in the
// UI. So the blob carries the obfuscated config PLUS a password verifier (a salted, stretched
// hash) — never the plaintext password. Reveal recomputes the verifier and compares. This is
// just enough to deter casual peeking at a shared population sampler.
function deriveKey(password, salt) {
  // Cheap, dependency-free key stretch: FNV-style fold of password+salt into a fixed
  // 64-char printable-ASCII keystream. (Deterministic; not a KDF — see note above.)
  const seed = password + "::" + salt;
  let h = 2166136261 >>> 0;
  let out = "";
  for (let i = 0; i < 64; i++) {
    h ^= seed.charCodeAt(i % seed.length) || 0;
    h = Math.imul(h, 16777619) >>> 0;
    out += String.fromCharCode(33 + (h % 94)); // printable ASCII, < 128
  }
  return out;
}
// XOR each char against the repeating key. Operates on base64 text (chars < 128) so the
// result stays < 128 (plain ASCII, possibly control chars) and survives JSON round-trips.
function xorCipher(str, key) {
  let out = "";
  for (let i = 0; i < str.length; i++) out += String.fromCharCode(str.charCodeAt(i) ^ key.charCodeAt(i % key.length));
  return out;
}
function randomSalt() {
  return Math.random().toString(36).slice(2, 10);
}
// Password verifier stored in a hidden blob so Reveal can check the password without keeping
// it. A salted, stretched derivation of the password (deterministic ⇒ a correct password
// reproduces the same string); the plaintext never travels.
function pwVerifier(password, salt) {
  return deriveKey(password, salt + "::pw");
}

// Encode app state → a URL-safe blob string (the value of the ?s= param).
// opts.password (optional) produces a HIDDEN blob: the config is concealed behind the
// password while the sampler still runs for whoever opens the link.
export function encodeConfig(state, opts) {
  const config = pickConfig(state);
  const password = opts && opts.password;
  let envelope;
  if (password) {
    const salt = randomSalt();
    // Obfuscate with a code-known key (NOT the password) so the sampler runs for anyone who
    // opens the link; store a password verifier so Reveal can gate viewing the internals.
    const inner = LZString.compressToBase64(JSON.stringify(config));
    const data = xorCipher(inner, deriveKey(PEPPER, salt));
    envelope = { v: VERSION, hidden: true, salt, pw: pwVerifier(password, salt), data };
  } else {
    envelope = { v: VERSION, hidden: false, config };
  }
  return LZString.compressToEncodedURIComponent(JSON.stringify(envelope));
}

// Decode a blob → one of:
//   null                                  (absent/garbled/unsupported version)
//   { hidden:false, config }              (ready to load)
//   { hidden:true, salt, pw, config }     (load+run concealed at once — no password needed;
//                                          `salt`+`pw` gate a later Reveal via
//                                          checkHiddenPassword)
export function decodeConfig(blob) {
  if (!blob) return null;
  let envelope;
  try {
    const json = LZString.decompressFromEncodedURIComponent(blob);
    if (!json) return null;
    envelope = JSON.parse(json);
  } catch { return null; }
  if (!envelope || envelope.v !== VERSION) return null;
  if (envelope.hidden) {
    if (!envelope.salt || !envelope.data) return null;
    // Recover the config with the code-known PEPPER so the sampler runs concealed on open.
    try {
      const inner = xorCipher(envelope.data, deriveKey(PEPPER, envelope.salt));
      const json = LZString.decompressFromBase64(inner);
      if (!json) return null;
      const config = JSON.parse(json);
      if (!config || !Array.isArray(config.pipeline)) return null;
      return { hidden: true, salt: envelope.salt, pw: envelope.pw, config };
    } catch { return null; }
  }
  if (!envelope.config || !Array.isArray(envelope.config.pipeline)) return null;
  return { hidden: false, config: envelope.config };
}

// Reveal gate: verify a password against the stored verifier. The plaintext password is
// never stored or transmitted — only this salted, stretched derivation is compared.
export function checkHiddenPassword(salt, pwStored, password) {
  return !!salt && !!pwStored && pwVerifier(password, salt) === pwStored;
}

// Build a full shareable URL for the current page from a blob.
export function shareURL(blob) {
  const base = window.location.origin + window.location.pathname;
  return base + "?s=" + blob;
}
